### ISSUE TITLE
run errors

### ISSUE THREAD

**Issue by earthbound19** [tehmoon/cryptocli#3]
I get this error attempting run from the `master`, `add_filters`, or `ebu_dev` branches:

```
go run main.go

# command-line-arguments
.\main.go:38:20: undefined: newByteCounter
.\main.go:39:21: undefined: newByteCounter
```

the `ebu_dev` branch adds:

```
.\main.go:38:20: undefined: newByteCounter
.\main.go:39:21: undefined: newByteCounter
```

Is there a dependency on a specific checkout state of any of the repositories this project relies on in `/go/src`?

**Comment by earthbound19** [comment]
Never mind, I solved it I think.

A [genius breath yonder](https://stackoverflow.com/a/28153553/1397555) says I need to list all go files with `run`. When I run `go run main.go byteCounter.go` it gives CLI instructions and no errors.

.. and extending with an example command:

```
echo -n toto | go run main.go bytecounter.go dd -encoders binary-string
00101101011011100010000001110100011011110111010001101111001000000000110100001010
```

**Comment by tehmoon** [comment]
> A genius breath yonder says I need to list all go files with run. When I run go run main.go byteCounter.go it gives CLI instructions and no errors.

Yes that is true, though I prefer building the binary for "larger" project with `go build` directly. Otherwise `go run *.go` will run the binary after building it in a temporary directory.
